id: "web-server"
image: "nginx"
tag: "latest"
port: 80
containerPort: 80
path: /
resources:
  cpu: 1m
  memory: 6Mi
  memoryLimit: 12Mi

ingress:
  enabled: false

service:
  enabled: false
  additionalPorts: []

secretRefs: []
configMapRefs: []
env: {}
configMapMounts: []

security:
  permissionPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
  contentSecurityPolicy: >-
    default-src 'self';
    script-src 'self';
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: https:;
    font-src 'self' data:;
    connect-src 'self';
    object-src 'none';
    base-uri 'self';
    frame-ancestors 'self';
    form-action 'self';
  crossOriginEmbedderPolicy: "require-corp"

global:
  ingress:
    fqdn: "example.com"
    className: "traefik"
    certManager:
      issuer: ""
    traefik:
      certResolver: ""
